### ISSUE TITLE
UIEnvelope requests too little space

### ISSUE THREAD

**Issue by burksbuilds** [dirkhillbrecht/UiUiUi#11]
The UIEnvelope class requests a preferred size based on calling the UISize.cumulateBoth() function to add together the content preferred size and the width/height specified in the 'border' UISize field. The cumulateBoth function adds the width and height of the input UISize **once** to the output UISize. However, the 'width' and 'height' fields of the UISize border field represent a symmetric thickness that should be applied to both sides of the contained widget, so they should actually be added **TWICE** to the output UISize.

**Comment by dirkhillbrecht** [comment]
Merged into master, will be included in next release
