### ISSUE TITLE
Horizontal and Vertical lines impact group sizing

### ISSUE THREAD

**Issue by burksbuilds** [dirkhillbrecht/UiUiUi#13]
UIHorizontalLine and UIVerticalLine currently request infinite (UISize::MAX_LEN) space in their 'axial' direction. The effect of this when they are grouped, perhaps as a visual divider, between widgets that request a finite size in that direction is that the layout engine over-allocates space to the entire group. Because the lines will draw along the entire length allocated to them they already effectively 'grow' in their 'axial' direction, so they do not need to request that extra space.

**Comment by dirkhillbrecht** [comment]
Merged into master, will be included in next release.
